#-------------------------------
# Site Settings

title: Liam McKane
logo: # You can add own logo. For example '/images/logo.png'.
description: My Personal Portfolio

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'The Engineer'
      url: '/engineer'
    - title: 'The Artist'
      url: '/artist'
    # - title: 'The Voice'
    #   url: '/voice'
    - title: 'Resume'
      url: '/LiamMcKaneResume.pdf'
        # - title: 'Posts'
    #   url: '/blog/'
    # - title: 'Pages'
  # submenu:
   
      # - url: '/elements'
      #   title: 'Elements'

# Call to action button
cta__button__text: Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/pastel.jpg'


#-------------------------------
# Author Settings

author:
  name: Liam McKane
  title: Hello, I’m Liam McKane
  bio: I’m a Quality Engineer at Alarm.com with a B.S. in Computer Engineering from George Mason University. I specialize in embedded systems, machine learning, and robotics—building intelligent systems that bridge hardware and software.

Beyond engineering, I’m passionate about visual design and creative expression. Whether I’m debugging hardware, developing autonomous systems, or illustrating a digital portrait, I enjoy projects that let me merge logic with creativity.

This site showcases my technical work, creative projects, and ongoing journey as a multidisciplinary engineer.

experience:
  microstrategy: 
  alarmcom:
#-------------------------------
# Projects Settings

projects__settings:
  projects__title: My <span class="text-span">Projects</span> # Add a 'text-span' class to highlight text.
  projects__description: A showcase of my class and personal projects.


#-------------------------------
# Testimonials Section

# testimonial__title: My Happy <span class="text-span">Clients</span> # Add a 'text-span' class to highlight text.

# testimonial-items:
#   - name: "Zaire Baptista"
#     image: "/images/client-1.jpg"
#     designation : "Traveler"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

#   - name: "Ann Philips"
#     image: "/images/client-2.jpg"
#     designation : "Designer"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

#   - name: "Roger Bergson"
#     image: "/images/client-3.jpg"
#     designation : "CEO, Founder"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

#   - name: "Julie Arnold"
#     image: "/images/client-4.jpg"
#     designation : "Full stack developer"
#     content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

# blog__settings:
#   blog__title: Recent <span class="text-span">Blog</span> Posts # Add a 'text-span' class to highlight text.
#   blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: me@liammckane.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Let's work together! # Add a description to your form


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier.
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/LiamJMcKane"}
- {icon: "ion-logo-github", link: "https://github.com/lmckane"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/liam-mckane/"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com"}